version: '2'
services:
    jirareport-app:
        image: jirareport
        external_links:
            - jirareport-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jiraReport
        ports:
            - 8080:8080
    jirareport-mongodb:
        extends:
            file: mongodb.yml
            service: jirareport-mongodb
